name: Build Android on Push

on:
  push:
    branches:
      - main   # Change cette branche si tu veux build sur une autre

jobs:
  call-build:
    uses: ./.github/workflows/build-android-e2e.yml
    with:
      build_type: main
      metamask_environment: qa
      keystore_target: qa
